apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go
  namespace: dev 
  labels:
    app: example-go
spec:
  selector:
    matchLabels:
      app: example-go
  template:
    metadata:
      labels:
        app: example-go
    spec:
      containers:
      - name: example-go
        image: ghcr.io/alokhom/oci-repo/goimage
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ocicred
---